// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9trhxtm6VM8grCK32sZPG9CmVgkxvlU',
    appId: '1:326099273958:web:a13c24155639867af25327',
    messagingSenderId: '326099273958',
    projectId: 'paintings-identifier',
    authDomain: 'paintings-identifier.firebaseapp.com',
    storageBucket: 'paintings-identifier.firebasestorage.app',
    measurementId: 'G-7L76KGB1R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QriVrOlq3-u772DVf684CJN8HqNS6kU',
    appId: '1:326099273958:android:d4a78dabe428668df25327',
    messagingSenderId: '326099273958',
    projectId: 'paintings-identifier',
    storageBucket: 'paintings-identifier.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vp9K6MmoHM0_SxaBEKp6WBPQtE2Vcfw',
    appId: '1:326099273958:ios:949c3ac28b93e7b3f25327',
    messagingSenderId: '326099273958',
    projectId: 'paintings-identifier',
    storageBucket: 'paintings-identifier.firebasestorage.app',
    iosClientId: '326099273958-4cfdchbv610prvf0u0ue2ekt19co5046.apps.googleusercontent.com',
    iosBundleId: 'com.veradostudio.artlore',
  );
}
